apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    app.edp.epam.com/codebase: javaee-legacy-app-example
    app.edp.epam.com/codebasebranch: javaee-legacy-app-example-master
    app.edp.epam.com/pipelinetype: build
  name: javaee-legacy-app-example-master-build-rand
  namespace: dx-dev
spec:
  params:
    - name: git-source-url
      value: ssh://git@github.com:22/edp-dx/javaee-legacy-app-example
    - name: git-source-revision
      value: master
    - name: CODEBASEBRANCH_NAME
      value: javaee-legacy-app-example-master
    - name: CODEBASE_NAME
      value: javaee-legacy-app-example
  pipelineRef:
    name: github-legacy-java-app-build-edp
  serviceAccountName: tekton
  taskRunSpecs:
    - pipelineTaskName: create-ecr-repository
      taskServiceAccountName: edp-kaniko
    - pipelineTaskName: kaniko-build
      taskServiceAccountName: edp-kaniko
  timeout: 1h0m0s
  workspaces:
    - configMap:
        name: custom-legacy-settings
      name: settings
    - name: shared-workspace
      subPath: codebase
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: ssh-creds
      secret:
        secretName: github
